
services:

  fastapi:
    container_name: fastapi
    build:
      context: .
    command: sh -c "./src/scripts/fastapi.sh"

    ports:
      - "2000:2000"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6378:6379'
    volumes:
      - redis:/data

volumes:
  redis: