
services:

  fastapi:
    container_name: fastapi
    build:
      context: .
    command: sh -c "./src/scripts/fastapi.sh"

    ports:
      - "2000:2000"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6378:6379'
    volumes:
      - redis:/data
  
  chromadb:
    image: chromadb/chroma:latest
    volumes:
      - ./chromadb:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma # this is the default path, change it as needed
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
    ports:
      - 8100:8000

volumes:
  redis: